// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yduosziameskzofrcodg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkdW9zemlhbWVza3pvZnJjb2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzM0MDAsImV4cCI6MjA3MTk0OTQwMH0.jegAqUAGcao8KoU7UxAk_I_At1p2mOgxfKVrJKKHlpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});